In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('E:\ML 2026\Data.csv')

In [3]:
x=dataset.iloc[:, :-1].values
y=dataset.iloc[:, -1].values

In [4]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [5]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [6]:
from sklearn.impute import SimpleImputer

In [7]:
print(dataset.isnull().sum)

<bound method DataFrame.sum of    Country    Age  Salary  Purchased
0    False  False   False      False
1    False  False   False      False
2    False  False   False      False
3    False  False   False      False
4    False  False    True      False
5    False  False   False      False
6    False   True   False      False
7    False  False   False      False
8    False  False   False      False
9    False  False   False      False>


In [8]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:, 1:3])

SimpleImputer()

In [9]:
x[:, 1:3]=imputer.transform(x[:, 1:3])

In [10]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [12]:
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')

In [13]:
ct.fit_transform(x)

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [14]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [15]:
x=np.array(ct.fit_transform(x))

In [16]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
l=LabelEncoder()
l.fit_transform(y)

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [19]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [20]:
y=l.fit_transform(y)

In [21]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [22]:
x
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=1)

In [25]:
print(x_train)

[[1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [26]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]]


In [27]:
print(y_train)

[1 0 1 0 0 1 1 0 1]


In [28]:
print(y_test)

[0]


In [29]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [30]:
x_train[:, 3:5]=sc.fit_transform(x_train[:, 3:5])

In [31]:
print(x_train)

[[1.0 0.0 0.0 -0.41933001197089126 0.19342568291126377]
 [0.0 0.0 1.0 -0.1485518876488809 -1.1650263675926953]
 [0.0 1.0 0.0 0.03760807282250105 -0.09838994275254934]
 [1.0 0.0 0.0 0.6468588525470241 0.6462430330792501]
 [0.0 0.0 1.0 -0.2670173170397605 -0.3499551372903198]
 [0.0 0.0 1.0 -1.9424569612821991 -1.5272802477270844]
 [1.0 0.0 0.0 1.2561096322715473 1.280187323314431]
 [0.0 1.0 0.0 1.5607350221338088 1.64244120344882]
 [1.0 0.0 0.0 -0.7239554018331529 -0.6216455473911117]]


In [34]:
x_test[:, 3:]=sc.fit_transform(x_test[:, 3:])

In [35]:
print(x_test)

[[0.0 1.0 0.0 0.0 0.0]]
